
name: 'dbt_projects'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'Instacart_dbt_projects'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  Instacart_dbt_projects:
    # Config indicated by + and applies to all files under models/marts/instacart
    # marts:
    #   +materialized: table
    #   +schema: dev
    # staging:
    #   +materialized: view
    #   +schema: dev
    # intermediate:
    #   +materialized: view
    #   +schema: dev