--profit generated by departments

WITH pro AS (
  SELECT *
  FROM {{ref ('stg_products')}}
),
departments AS (
  SELECT *
  FROM {{ref ('stg_department')}}
),
orders as (
    select * from {{ref ('stg_orders')}}
),
aisles as (
  select * from {{ref ('stg_aisles')}}
)
SELECT  
	   COALESCE(department, 'Total Profit') as department,
      SUM((unit_price - unit_cost) * quantity) as profit
FROM pro 
JOIN departments ON pro.department_id = departments.department_id

JOIN aisles ON pro.aisle_id = aisles.aisle_id

JOIN orders on pro.product_id = orders.product_id

GROUP BY ROLLUP (department) 

order by profit desc

OFFSET 1